[project]
name = "beachvar-device"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pydantic>=2.12.5",
    "python-dotenv>=1.2.1",
    "websockets>=15.0.1",
]
